#!/usr/bin/env bash

set -euo pipefail

source "$DOTLY_PATH/scripts/core/_main.sh"

##? Completely clean the docker environment.
#?? 1.0.0
##?
##? Usage:
##?   armageddon
docs::parse "$@"

dot docker remove_containers
docker network prune -f
docker rmi -f $(docker images --filter dangling=true -qa)
docker volume rm $(docker volume ls --filter dangling=true -q)
docker rmi -f $(docker images -qa)